services:
  postgres: 
    image: postgres
    container_name: school-spreadsheet-db
    restart: always

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 2s
      retries: 20

    ports:
      - "5431:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - school-spreadsheet

  school-spreadsheet-api:
    build: .
    image: school-spreadsheet-api
    container_name: school-spreadsheet-api
    env_file:
      - .env
    ports:
      - "5001:5001"

    depends_on:
      - postgres
    networks:
      - school-spreadsheet
      - web
    
networks:
  school-spreadsheet:
    driver: bridge
  
  web:
    external: true
  
    
volumes:
  postgres_data: